In [45]:
import numpy as np

In [50]:
#generate list of numbers from 0 - 5
print(list(range(5)))

for num in range(5):
    print(num)

[0, 1, 2, 3, 4]
0
1
2
3
4


In [53]:
#list comprehenhension
x = [1,2,3,4]
[item**2 for item in x]

[1, 4, 9, 16]

In [57]:
#map with lambda
seq = [1,2,3,4,5]
list(map(lambda var: var*2,seq))

[2, 4, 6, 8, 10]

In [56]:
#filter with lambda
seq = [1,2,3,4,5]
list(filter(lambda item: item%2 == 0,seq))

[2, 4]

In [2]:
#numbers between 0 and 20 in steps of 2
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [5]:
#matrix of 0 by 3x3
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [7]:
#array of 0 with length 5
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [10]:
#5 linearly distrubted numbers between 0 and 1
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [12]:
#idenitiy matrix 4x4
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [14]:
#5x5 list of numbers bewtween 0 - 1
np.random.rand(5,5)

array([[0.04687571, 0.02062594, 0.60982193, 0.80253088, 0.86195706],
       [0.31504183, 0.27298132, 0.53953402, 0.36303888, 0.05392289],
       [0.93340664, 0.77202961, 0.84314392, 0.9543811 , 0.89201873],
       [0.54503521, 0.85000197, 0.44953226, 0.72245567, 0.70594715],
       [0.3952221 , 0.0344152 , 0.82125856, 0.53107206, 0.32866965]])

In [15]:
#standard normal distribution
np.random.randn(4)

array([ 0.74202052, -0.30677913, -0.16682783,  0.69083294])

In [17]:
np.random.randint(0,100)

63

In [28]:
#25 random numbers bewtween 0 - 50
ranarr = np.random.randint(0,50,25)
print(ranarr)

#reshape list to 5x5
twod = ranarr.reshape(5,5)
print(twod)

print(twod.max())
#index of max number
print(twod.argmax())
print(twod.min())
print(twod.argmin())

[33 22 26 14 29 25  1 32 26 48 43 41 12 46 41 33 30 18 29  3 36 23 45  4
 14]
[[33 22 26 14 29]
 [25  1 32 26 48]
 [43 41 12 46 41]
 [33 30 18 29  3]
 [36 23 45  4 14]]
48
9
1
6


In [44]:
#broadcasting an array is by reference
arr = np.arange(0,20,5)
print (arr)

#copy array
arr_copy = arr.copy()

slice = arr[0:2]
slice[:] = 100
print (arr)


print (arr_copy)

[ 0  5 10 15]
[100 100  10  15]
[ 0  5 10 15]


In [63]:
arr_2d = np.array([[1,2],[3,4],[5,6]])

#same as [2][1]
print(arr_2d[2,1])

#list of all items with index 1 from all arrays up to index 2
print(arr_2d[:2,1])


#list of lists with index lower than 2 and their items with index greater than 1
print(arr_2d[:2,1:])

6
[2 4]
[[2]
 [4]]


In [71]:
#conditional selecting
arr = np.arange(1,11)
print(arr)

#get boolean array by condition
bool_arr = arr > 5
print(bool_arr)

#get all items that apply to condition
print(arr[bool_arr])

#short
print(arr[arr > 5])

[ 1  2  3  4  5  6  7  8  9 10]
[False False False False False  True  True  True  True  True]
[ 6  7  8  9 10]
[ 6  7  8  9 10]


In [77]:
#array operations
arr = np.arange(0,11)
print (arr+arr)
print (arr*10)

#division by zero
print(arr/arr)

[ 0  2  4  6  8 10 12 14 16 18 20]
[  0  10  20  30  40  50  60  70  80  90 100]
[nan  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]


/home/jonas/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:6: RuntimeWarning: invalid value encountered in true_divide
  


In [81]:
#universal array functions
arr = np.arange(0,11)
print(arr)
print(np.exp(arr))
print(np.sin(arr))
print(np.max(arr))

[ 0  1  2  3  4  5  6  7  8  9 10]
[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03 2.20264658e+04]
[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849 -0.54402111]
10
